#!/usr/bin/env python
import os, re, subprocess, sys

def decode(m):
  out = subprocess.check_output(['./fp-repr', 'float', m.group(1)])
  return out[:-1]

def main():
  if len(sys.argv) != 2:
    print 'usage: {0} [file]'.format(sys.argv[0])
    sys.exit()

  f = open(sys.argv[1], 'r')
  os.chdir(sys.path[0])

  for line in f:
    print re.sub(r'\%FP\((.*?)\)', decode, line),
  f.close()

if __name__ == "__main__":
  main()

